---
title: "combine_wordbag_2grams"
author: "Xuran Zhang"
date: "5/1/2017"
output: pdf_document
---

```{r}
library(readr)
library(randomForest)
library(pls)

library(stringr)
library(tidyr)
require(RJSONIO)
library(dplyr)
library(plyr)
require(doMC)
registerDoMC(cores=4)
library(zoo)
library(rARPACK)
library(gbm)
```

```{r}
wordbag_data = read.csv("wordbagCleanTrainAndTest.csv")
# delete first column and review_stars for wordbag_data
wordbag_data = wordbag_data[,-c(1,811)]
#  dim(wordbag_data)  138393    809
grams_data = read.csv("review_2grams_TrainAndTest.csv")
grams_3_data = read.csv("review_3grams_TrainAndTest.csv")
# dim(grams_3_data)
grams_data = grams_data[,-1]
grams_3_data = grams_3_data[,-c(1,900)]
# dim(grams_data)  138393    951
# dim(grams_3_data) 138393    898 
review_test <- read.csv('yelp_academic_dataset_review_test.csv')
```

```{r}
a <- read.csv("yelp_academic_dataset_review_train.csv")
c <- as.matrix(a$business_id)
d <- as.matrix(review_test$business_id)
dim(d)
b <- rbind(c,d)
dim(b)
combine_wordbag_grams = cbind(wordbag_data, grams_3_data,grams_data,b)
# dim(combine_wordbag_grams)


# colnames(combine_wordbag_grams) = c(as.character(1:1759), "review_stars")
colnames(combine_wordbag_grams) = c(as.character(1:2657), "review_stars","business_id")
write.csv(combine_wordbag_grams, "review_clean_wordbag_grams_3grams_TrainAndTest_withBusId.csv")


combine_wordbag_grams <- (read.csv("review_clean_wordbag_grams_3grams_TrainAndTest_Clean.csv"))[,-1]
dim(combine_wordbag_grams)
X_train = combine_wordbag_grams[1:116474,]
X_test = combine_wordbag_grams[116475:138393,]
# try randoomForest can't get prediction, run one day 
## colnames(combine_wordbag_grams) = c(as.character(1:1759), "review_stars")
# X_train_X = combine_wordbag_grams[1:116474,-1760]
# X_train_Y = combine_wordbag_grams[1:116474,1760]
# X_test = combine_wordbag_grams[116475:138393,-1760]
X_train_X = combine_wordbag_grams[1:116474,-2658]
X_train_Y = combine_wordbag_grams[1:116474,2658]
X_test = combine_wordbag_grams[116475:138393,-2658]
```

#For PCA
```{r}
X = combine_wordbag_grams[,-1760]
X.pca = prcomp(X, center = T, scale = T)
```
```{r}
plot(X.pca$sdev[1:50])
```


```{r}
#prcomp
#lin_mod = pcr(X_train_Y ~ as.matrix(X_train_X), scale = T, validation = "CV")
```

```{r}
# lin_mod = gbm(review_stars~., data = X_train, distribution = "adaboost", interaction.depth = 2, n.tree = 100, verbose = TRUE)
# lin_mod <- randomForest(X_train_X, as.factor(X_train_Y),nodesize = 5000, maxnodes = 20,ntree = 500)
#pred = as.numeric(predict(lin_mod, newdata = X_test))


# # Fit linear model
boosting <- gbm(review_stars ~., data = X_train[,-2659], distribution = "gaussian", interaction.depth = 3, n.trees = 150, verbose = F)
which(colnames(X_train) == "business_id")
which(colnames(X_train) == "review_id")
which(colnames(X_train) == "review_stars")
which(is.na(X_train$review_stars ))

#lin_mod = glm(review_stars ~. , data = X_train)
pred = predict(lin_mod, newdata = X_test)
#yulaoban = function(x){
#  min(5, max(1, x))
#}

#pred = sapply(pred, yulaoban)
xuran_2grams_output = cbind(as.vector(review_test$business_id), pred)
colnames(xuran_2grams_output) = c("business_id", "stars")
# write.csv(xuran_2grams_output, file = "xuran_combine_wordbag_grams_output.csv")
write.csv(xuran_2grams_output, file = "boosting.csv")
reviews = read.csv("boosting.csv")
bus = read.csv("yelp_academic_dataset_business_test.csv")

reviews_by_bus = reviews %>% 
  spread(key = business_id, value = stars)
bus_star_mean = colMeans(reviews_by_bus, na.rm=TRUE) %>% 
  data.frame()


match = function(bid){
  row_i = which(bid == rownames(bus_star_mean))
  star = bus_star_mean[row_i,]
  star
}
stars = sapply(bus$business_id, match)
bus_output = cbind(bus, stars)
review_output = cbind(as.vector(bus_output$business_id),bus_output$stars)
colnames(review_output) = c("business_id", "stars")

# write.csv(review_output,"xuran_combine_wordbag_grams_rForest_kaggle.csv")
write.csv(review_output,"boosting_kaggle.csv")
```

