---
title: "Reviews_to_Res"
author: "Wenjun Zeng"
date: "4/29/2017"
output: html_document
---

```{r}
library(readr)
library(stringr)
library(tidyr)
require(RJSONIO)
library(dplyr)
library(plyr)
require(doMC)
registerDoMC(cores=4)
library(zoo)
library(rARPACK)
```



```{r}
# This .Rmd include all methond that I use to get mean for all business_id to get 
# the mean of stars for each business_id.


# reviews = read.csv("xuran_wordbag_output.csv")
# reviews = read.csv("xuran_wordbag_lasso_output.csv")
#####reviews = read.csv("xuran_wordbag_pca_output.csv")
# reviews = read.csv("xuran_wordbag_ridge_output.csv")
# reviews = read.csv("xuran_combine_wordbag_grams_output.csv")
reviews = read.csv("xuran_combine_wordbag_grams_rForest_output.csv")
# reviews = read.csv("xuran_2grams_output.csv")
# reviews = read.csv("xuran_2grams_lasso_output.csv")
bus = read.csv("yelp_academic_dataset_business_test.csv")
```


```{r}
reviews_by_bus = reviews %>% 
  spread(key = business_id, value = stars)
bus_star_mean = colMeans(reviews_by_bus, na.rm=TRUE) %>% 
  data.frame()


match = function(bid){
  row_i = which(bid == rownames(bus_star_mean))
  star = bus_star_mean[row_i,]
  star
}
stars = sapply(bus$business_id, match)
bus_output = cbind(bus, stars)

review_output = cbind(as.vector(bus_output$business_id),bus_output$stars)
colnames(review_output) = c("business_id", "stars")

# write.csv(review_output,"review_output_Kaggle.csv")
##### write.csv(review_output,"xuran_wordbag_pca_kaggle.csv")
# write.csv(review_output,"xuran_wordbag_ridge_kaggle.csv")
# write.csv(review_output,"xuran_wordbag_lasso_kaggle.csv")

# write.csv(review_output,"review_2gram_Kaggle.csv")
# write.csv(review_output,"xuran_2gram_lasso_Kaggle.csv")
# write.csv(review_output,"xuran_combine_wordbag_grams_glm_kaggle.csv")
write.csv(review_output,"xuran_combine_wordbag_grams_rForest_kaggle.csv")
```